# Generated by Django 5.0.4 on 2024-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='servico',
            name='especialidade',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='servico',
            name='profissionais',
            field=models.ManyToManyField(related_name='servicos', to='landing_page.profissional'),
        ),
    ]
